### ISSUE TITLE
Broken slugs in admin create

### ISSUE THREAD

**Issue by bobbyesh** [eSmelser/SnookR#10]
Should be replaced with AutoSlugField

**Comment by eSmelser** [comment]
@bobbyesh 
So I was thinking that the point of having the slug field is that you wouldn't have to/be able to populate it upon instance creation, yeah? Shouldn't they get auto-populated upon creation and essentially represent the instance name (whatever that might be) without any whitespace? Or am I misunderstanding their intended purpose?

**Comment by bobbyesh** [comment]
Yep.  The slug is so that each model instance has a URL-friendly name, which should be auto-generated from other fields from the model and should be unique.
