### ISSUE TITLE
Bug introduced with Session Creation

### ISSUE THREAD

**Issue by eSmelser** [eSmelser/SnookR#13]
New bug introduced preventing me from creating new sublists because Sessions cannot be created.

**Comment by eSmelser** [comment]
The bug must have been with the data set on one of the SnookR instances I stood up, because I can't repeat it on my home computer. I'm guessing it has to do with having players in the system without all of the required fields that now exist in player instantiation, but I'm not sure. Will do more testing next week.

**Comment by bobbyesh** [comment]
old
