### ISSUE TITLE
Admin and main urls conflicting

### ISSUE THREAD

**Issue by bobbyesh** [eSmelser/SnookR#7]
Some URL redirects and links lead to the admin user pages, instead of the main URLs.

**Comment by eSmelser** [comment]
@bobbyesh do you have any examples of which ones, or of what you think may be causing the issue?

**Comment by bobbyesh** [comment]
@eSmelser I realized that the problems were not in the home-page branch I pushed up to origin, and just on my local, and only after adding  'password change' views for users.  The extra functionality and fixes will be in my next pull request.

**Comment by eSmelser** [comment]
@bobbyesh is this still an issue? Or can we close it? If it is, what needs to be done exactly?

**Comment by bobbyesh** [comment]
Fixed.
